### PR TITLE
Support DataFrames 0.22

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR adds 0.22 to the compat versions of DataFrames.

### CODE REVIEW

**Comment by mohamed82008** [comment]
DataFrames 0.22 was used in the tests https://github.com/JuliaSmoothOptimizers/SolverTools.jl/runs/2106616866#step:5:20.

**Comment by abelsiqueira** [comment]
Thanks @mohamed82008. I'll prepare a release.

**Comment by abelsiqueira** [comment]
By the way, has DataFrames 0.22 been out long? Our CompatHelper should have picked it up.

**Comment by mohamed82008** [comment]
Ya it's been a while. I don't know why CompatHelper hasn't picked it up.

**Comment by abelsiqueira** [comment]
I found out why. There was no activity for over 2 months, and the Action turned off.

**Pull request merged**
